name: Run Pytests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compile PointNet++ CUDA layers for PSTNet
      run: |
        cd src/model/PSTNet/modules/pointnet2_ops_lib
        python setup.py install

    - name: Run tests
      run: |
        pytest src/model
