name: Run PyTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install other dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.0.1 --extra-index-url https://download.pytorch.org/whl/cu118
        pip install -r requirements.txt --extra-index-url https://data.pyg.org/whl/torch-2.0.1+cu118.html

    - name: Compile PointNet++ CUDA layers for PSTNet
      run: |
        cd src/model/PSTNet/modules/pointnet2_ops_lib
        python setup.py install

    - name: Run tests
      run: |
        pytest src/model
